### ISSUE TITLE
using util.py script

### ISSUE THREAD

**Issue by WesScivetti** [pylogeny/concordance#5]
Hi all,

Sorry, I am having very some basic issues regarding using the util.py script. I am getting an attribute error regarding tree_dict.

Traceback (most recent call last):
  File "src/pyloconcordance/util.py", line 134, in <module>
    print(get_quartets(treeA))
  File "src/pyloconcordance/util.py", line 110, in get_quartets
    graph = as_graph(tree)
  File "src/pyloconcordance/util.py", line 24, in as_graph
    G = {node: [] for node in tree.tree_dict if node != tree.root.name}
AttributeError: 'Tree' object has no attribute 'tree_dict'

I've looked through the pylotree script, and I don't see a reference to tree_dict, so I'm a bit confused. I ran python3 setup.py develop in the concordance and tree repositories, both of which I cloned to my Github desktop. I am new to Github in a development capacity so please let me know if there is a better way to do this. Thank you so much!

**Comment by LinguList** [comment]
yes, I already fixed that, you should pull again, this error is now gone.

**Comment by LinguList** [comment]
so the problem is only that you did not have the data in sync.

**Comment by WesScivetti** [comment]
working now, thank you!
